apiVersion: apps/v1
kind: Deployment
metadata:
  name: &PODNAME monitoring-opensearch
spec:
  replicas: 1
  strategy:
    # recreate to avoid simultanopus locking of the data volume during updates
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/component: *PODNAME
  template:
    metadata:
      labels:
        app.kubernetes.io/component: *PODNAME
    spec:
      volumes:
      - name: *PODNAME
        persistentVolumeClaim:
          claimName: *PODNAME
      initContainers:
      - name: fsgroup-volume
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ['sh', '-c']
        args:
        # change data ownership to avoid "permision denied" errors
        - 'chown -R 1000:1000 /usr/share/opensearch/data'
        securityContext:
        runAsUser: 0
        resources:
        requests:
          cpu: 1m
          memory: 32Mi
        limits:
          cpu: 10m
          memory: 128Mi
        volumeMounts:
        - mountPath: /usr/share/opensearch/data
          name: *PODNAME
      containers:
      - name: *PODNAME
        image: opensearchproject/opensearch:latest
        volumeMounts:
          - mountPath: /usr/share/opensearch/data
            name: *PODNAME
        env:
          - name: discovery.type
            value: single-node
          - name: OPENSEARCH_JAVA_OPTS
            value: -Xms512m -Xmx512m
          - name: DISABLE_INSTALL_DEMO_CONFIG
            value: "true"
          - name: DISABLE_SECURITY_PLUGIN
            value: "true"
        ports:
          - name: api
            containerPort: 9200
          - name: performance
            containerPort: 9600