apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/component: grafana

resources:
- deployment.yaml
- pvc.yaml
- service.yaml


configMapGenerator:
  - name: grafana-config
    files:
    - params/grafana.ini
  - name: grafana-datasources
    files:
    - params/prometheus-datasource.yaml