apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
spec:
  template:
    spec:
      containers:
      - name: fluent-bit
        env:
        - name: FLUENT_OPENSEARCH_HOST
          value: monitoring-opensearch.wac-hospital
        - name: FLUENT_OPENSEARCH_PORT
          value: "9200"