apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: logging
  labels:
    k8s-app: fluent-bit
data:
  # Configuration files: server, input, filters and output
  # ======================================================
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Log_Level     info
        Daemon        off
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    @INCLUDE input-kubernetes.conf
    @INCLUDE filter-kubernetes.conf
    @INCLUDE output-opensearch.conf

  output-opensearch.conf: |
    [OUTPUT]
        Name                opensearch
        Match               *
        Host                ${FLUENT_OPENSEARCH_HOST}
        Port                ${FLUENT_OPENSEARCH_PORT}
        Suppress_Type_Name  On
        Replace_Dots        On
        Retry_Limit         2

  output-elasticsearch.conf: null