apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
 app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

resources:
- prepare.kustomization.yaml
- cd.kustomization.yaml
- install.kustomization.yaml
- secrets.kustomization.yaml
- git-repository.yaml
- ambulance-ufe.image-repository.yaml
- ambulance-ufe.image-policy.yaml
- ufe-controller.image-repository.yaml
- ufe-controller.image-policy.yaml
- ambulance-webapi.image-repository.yaml
- ambulance-webapi.image-policy.yaml
- image-update-automation.yaml

patches:
  - target:
      group: kustomize.toolkit.fluxcd.io
      version: v1
      kind: Kustomization
    patch: |-
      - op: add
        path: /spec/decryption
        value:
          provider: sops
          secretRef:
            name: sops-age