apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

secretGenerator:
  - name: repository-pat
    type: Opaque
    envs:
      - params/repository-pat.env
    options:
        disableNameSuffixHash: true