apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- http-route.yaml

namespace: wac-hospital

commonLabels:
  app.kubernetes.io/component: http-echo